#!/usr/bin/env python

import sys
from git import Repo


def main():
    repo = Repo('.')
    active_branch = repo.active_branch
    if (active_branch.name == 'master'):
        print('No commits to master allowed. Please create a feature branch.')
        sys.exit(1)
    else:
        print('Current branch: {}'.format(active_branch.name))

if __name__ == '__main__':
    main()
