#!/usr/bin/env python

import sys
from git import Repo


def main():
    repo = Repo('.')
    if not repo.head.is_detached:
        active_branch = repo.active_branch
        if active_branch.name is 'master':
            print('No commits to master allowed. Please create a feature branch.')
            sys.exit(1)

if __name__ == '__main__':
    main()
